var rule = {
    title:'drpy',
    host:'https://frodo.douban.com',
    apidoc:'https://www.doubanapi.com',
    homeUrl:'',
    searchUrl:'',
    searchable:1,
    quickSearch:1,
    filterable:1,
    // 分类链接fypage参数支持1个()表达式
    url:'/?pg=fypage&class=fyclass&douban=2297669',
    filter_url:'fl={{fl}}',
    图片来源:'@Referer=https://api.douban.com/@User-Agent=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/113.0.0.0%20Safari/537.36',
    headers:{
            "Host": "frodo.douban.com",
            // "Host": "api.douban.com",
            "Connection": "Keep-Alive",
            "Referer": "https://servicewechat.com/wx2f9b06c1de1ccfca/84/page-frame.html",
            // "content-type": "application/json",
            "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 MicroMessenger/7.0.9.501 NetType/WIFI MiniProgramEnv/Windows WindowsWechat"
    },
    timeout:5000,
    class_name:'热影HOTmovies&热剧HotTV&热综艺Hotvariety&电影movie&筛选filter',
    class_url:'hot_gaia&tv_hot&show_hot&movie&tv',
    filter:{'interests': [
	{'key': 'status', 'name': '状态STATUS', 'value': [
	{'n': '想看mark', 'v': 'mark'},
	{'n': '在看doing', 'v': 'doing'}, 
	{'n': '看过done', 'v': 'done'}
	]}, 
	{'key': 'subtype_tag', 'name': '形式TAG', 'value': [
	{'n': '全部ALL', 'v': ''}, 
	{'n': '电影MOVIE', 'v': 'movie'}, 
	{'n': '电视TV', 'v': 'tv'}
	]}, 
	{'key': '年代', 'name': '年代YEAR', 'value': [
	{'n': '全部ALL', 'v': ''}, 
	{'n': '2026', 'v': '2026'}, 
    {'n': '2025', 'v': '2025'}, 
    {'n': '2024', 'v': '2024'}, 
    {'n': '2023', 'v': '2023'}, 
    {'n': '2022', 'v': '2022'}, 
    {'n': '2021', 'v': '2021'}, 
    {'n': '2020', 'v': '2020'}, 
    {'n': '2019', 'v': '2019'}, 
    {'n': '2018', 'v': '2018'}, 
    {'n': '2017', 'v': '2017'}, 
    {'n': '2016', 'v': '2016'}, 
    {'n': '2015', 'v': '2015'}, 
    {'n': '2014', 'v': '2014'}, 
    {'n': '2013', 'v': '2013'}, 
    {'n': '2012', 'v': '2012'}, 
    {'n': '2011', 'v': '2011'}, 
    {'n': '2010', 'v': '2010'}, 
    {'n': '2010年代', 'v': '2010年代'},
    {'n': '2000年代', 'v': '2000年代'},
    {'n': '90年代', 'v': '90年代'}
	]}], 
	'hot_gaia': [
	{'key': 'sort', 'name': '排序SORT', 'value': [
	{'n': '热度recommend', 'v': 'recommend'}, 
	{'n': '最新time', 'v': 'time'}, 
	{'n': '评分rank', 'v': 'rank'}
	]}, 
	{'key': 'area', 'name': '地区AREA', 'value': [
	{'n': '全部ALL', 'v': '全部'}, 
	{'n': '中国CN', 'v': '华语'},  
    {'n': '韩国KR', 'v': '韩国'}, 
    {'n': '美国US', 'v': '欧美'}, 
    {'n': '日本JP', 'v': '日本'}
	]}], 
	'tv_hot': [{'key': 'type', 'name': '分类TYPE', 'value': [
	{'n': '综合HOT', 'v': 'tv_hot'}, 
	{'n': '中文剧CN','v': 'tv_domestic'},
    {'n': '美剧US','v': 'tv_american'},
    {'n': '日剧JP','v': 'tv_japanese'},
    {'n': '韩剧KR','v': 'tv_korean'},
    {'n': '动画animation','v': 'tv_animation'}
	]}], 
	'show_hot': [
	{'key': 'type', 'name': '分类Type', 'value': [
	{'n': '综合hot', 'v': 'show_hot'},
	{'n': '中国CN','v': 'show_domestic'},
    {'n': '国外other','v': 'show_foreign'}
	]}], 
	'movie': [
	{'key': '类型', 'name': '类型type', 'value': [
	{'n': '全部ALL', 'v': ''}, 
	{'n': '喜剧comedy', 'v': '喜剧'}, 
    {'n': '爱情romance', 'v': '爱情'}, 
    {'n': '动作action', 'v': '动作'}, 
    {'n': '科幻科幻', 'v': '科幻'}, 
    {'n': '动画cartoon', 'v': '动画'}, 
    {'n': '悬疑suspense', 'v': '悬疑'}, 
    {'n': '犯罪Crime', 'v': '犯罪'}, 
    {'n': '推理reasoning', 'v': '推理'}, 
    {'n': '法医Forensic', 'v': '法医'}, 
    {'n': '惊悚thriller', 'v': '惊悚'}, 
    {'n': '冒险adventure', 'v': '冒险'}, 
    {'n': '励志inspirational', 'v': '励志'}, 
    {'n': '警匪police', 'v': '警匪'}, 
    {'n': '小说novel', 'v': '小说'}, 
    {'n': '音乐music', 'v': '音乐'}, 
    {'n': '演唱会concert', 'v': '演唱会'}, 
    {'n': '奇幻fantasy', 'v': '奇幻'}, 
    {'n': '恐怖horror', 'v': '恐怖'}, 
    {'n': '战争WAR', 'v': '战争'}, 
    {'n': '复仇revenge', 'v': '复仇'}, 
    {'n': '网络电影Online', 'v': '网络电影'}, 
    {'n': '剧情drama', 'v': '剧情'},
    {'n': '穿越travel', 'v': '穿越'}, 
    {'n': '吸血鬼vampire', 'v': '吸血鬼'}, 
    {'n': '灾难disaster', 'v': '灾难'}, 
    {'n': '真实real', 'v': '真实'}, 
    {'n': '丧尸zombie', 'v': '丧尸'}, 
    {'n': '历史historical', 'v': '历史'}, 
    {'n': '纪录片documentary', 'v': '纪录片'}, 
    {'n': '传记biography', 'v': '传记'}
	]}, 
	{'key': '分类', 'name': '分类type', 'value': [
	{'n': '全部ALL', 'v': ''}, 
	{'n': '喜剧comedy', 'v': '喜剧'}, 
    {'n': '爱情romance', 'v': '爱情'}, 
    {'n': '动作action', 'v': '动作'}, 
    {'n': '科幻科幻', 'v': '科幻'}, 
    {'n': '动画cartoon', 'v': '动画'}, 
    {'n': '悬疑suspense', 'v': '悬疑'}, 
    {'n': '犯罪Crime', 'v': '犯罪'}, 
    {'n': '推理reasoning', 'v': '推理'}, 
    {'n': '法医Forensic', 'v': '法医'}, 
    {'n': '惊悚thriller', 'v': '惊悚'}, 
    {'n': '冒险adventure', 'v': '冒险'}, 
    {'n': '励志inspirational', 'v': '励志'}, 
    {'n': '警匪police', 'v': '警匪'}, 
    {'n': '小说novel', 'v': '小说'}, 
    {'n': '音乐music', 'v': '音乐'}, 
    {'n': '演唱会concert', 'v': '演唱会'}, 
    {'n': '奇幻fantasy', 'v': '奇幻'}, 
    {'n': '恐怖horror', 'v': '恐怖'}, 
    {'n': '战争WAR', 'v': '战争'}, 
    {'n': '复仇revenge', 'v': '复仇'}, 
    {'n': '网络电影Online', 'v': '网络电影'}, 
    {'n': '剧情drama', 'v': '剧情'},
    {'n': '穿越travel', 'v': '穿越'}, 
    {'n': '吸血鬼vampire', 'v': '吸血鬼'}, 
    {'n': '灾难disaster', 'v': '灾难'}, 
    {'n': '真实real', 'v': '真实'}, 
    {'n': '丧尸zombie', 'v': '丧尸'}, 
    {'n': '历史historical', 'v': '历史'}, 
    {'n': '纪录片documentary', 'v': '纪录片'}, 
    {'n': '传记biography', 'v': '传记'}
	]}, 
	{'key': '地区', 'name': '地区AREA', 'value': [
	{'n': '全部ALL', 'v': ''}, 
	{'n': '中国CN', 'v': '中国'}, 
    {'n': '香港HK', 'v': '香港'}, 
    {'n': '台湾TW', 'v': '台湾'}, 
    {'n': '韩国KR', 'v': '韩国'}, 
    {'n': '美国US', 'v': '美国'}, 
    {'n': '法国FRA', 'v': '法国'}, 
    {'n': '日本JP', 'v': '日本'}, 
    {'n': '马来西亚MY', 'v': '马来西亚'}, 
    {'n': '新加坡SG', 'v': '新加坡'}, 
    {'n': '泰国TH', 'v': '泰国'}, 
    {'n': '英国UK', 'v': '英国'}, 
    {'n': '俄罗斯RU', 'v': '俄罗斯'}, 
    {'n': '菲律宾PH', 'v': '菲律宾'}
	]}, 
{'key': '平台', 'name': '平台platform', 'value': [
	{'n': '全部ALL', 'v': ''}, 
	{'n': '腾讯TENXUN', 'v': '腾讯视频'},
	{'n': '爱奇艺AIQIYI', 'v': '爱奇艺'}, 
	{'n': '优酷YOUKU', 'v': '优酷'}, 
	{'n': '湖南HUNAN', 'v': '湖南卫视'},
	{'n': 'Netflix', 'v': 'Netflix'},
	{'n': 'HBO', 'v': 'HBO'}, 
	{'n': 'BBC', 'v': 'BBC'}, 
	{'n': 'NHK', 'v': 'NHK'}, 
	{'n': 'CBS', 'v': 'CBS'}, 
	{'n': 'NBC', 'v': 'NBC'}, 
	{'n': 'tvN', 'v': 'tvN'}
	]}, 
	{'key': '年代', 'name': '年代YEAR', 'value': [
	{'n': '全部ALL', 'v': ''}, 
	{'n': '2026', 'v': '2026'}, 
    {'n': '2025', 'v': '2025'}, 
    {'n': '2024', 'v': '2024'}, 
    {'n': '2023', 'v': '2023'}, 
    {'n': '2022', 'v': '2022'}, 
    {'n': '2021', 'v': '2021'}, 
    {'n': '2020', 'v': '2020'}, 
    {'n': '2019', 'v': '2019'}, 
    {'n': '2018', 'v': '2018'}, 
    {'n': '2017', 'v': '2017'}, 
    {'n': '2016', 'v': '2016'}, 
    {'n': '2015', 'v': '2015'}, 
    {'n': '2014', 'v': '2014'}, 
    {'n': '2013', 'v': '2013'}, 
    {'n': '2012', 'v': '2012'}, 
    {'n': '2011', 'v': '2011'}, 
    {'n': '2010', 'v': '2010'}, 
    {'n': '2010年代', 'v': '2010年代'},
    {'n': '2000年代', 'v': '2000年代'},
    {'n': '90年代', 'v': '90年代'}
	]}], 
	'tv': [
	{'key': '类型', 'name': '类型type', 'value': [
	{'n': '不限ALL', 'v': ''}, 
	{'n': '电视剧DRAMA', 'v': '电视剧'}, 
    {'n': '短剧SHOT', 'v': '短剧'}, 
    {'n': '动漫anime', 'v': '动漫'}, 
    {'n': '综艺TVSHOW', 'v': '综艺'}
	]}, 
	{'key': '电视剧分类', 'name': '电视剧DRAMA', 'value': [
	{'n': '不限ALL', 'v': ''}, 
	{'n': '古装costume drama', 'v': '古装'}, 
    {'n': '战争WAR', 'v': '战争'}, 
    {'n': '喜剧comedy', 'v': '喜剧'}, 
    {'n': '丧尸zombie', 'v': '丧尸'}, 
    {'n': '吸血鬼vampire', 'v': '吸血鬼'}, 
    {'n': '抗战War', 'v': '抗战'}, 
    {'n': '犯罪crime', 'v': '犯罪'}, 
    {'n': '推理reasoning', 'v': '推理'}, 
    {'n': '邢侦Detective', 'v': '刑侦'}, 
    {'n': '法医Forensic', 'v': '法医'}, 
    {'n': '警匪police', 'v': '警匪'}, 
    {'n': '动作action', 'v': '动作'}, 
    {'n': '科幻sci-fi', 'v': '科幻'}, 
    {'n': '奇幻fantasy', 'v': '奇幻'}, 
    {'n': '改编adaptation', 'v': '改编'}, 
    {'n': '小说novel', 'v': '小说'}, 
    {'n': '动画animation', 'v': '动画'}, 
    {'n': '剧情Drama', 'v': '剧情'}, 
    {'n': '青春youth', 'v': '青春'}, 
    {'n': '谍战Spy', 'v': '谍战'}, 
    {'n': '偶像idol', 'v': '偶像'}, 
    {'n': '纪录record', 'v': '纪录'}, 
    {'n': '都市metropolis', 'v': '都市'}, 
    {'n': '家庭family', 'v': '家庭'}, 
    {'n': '复仇revenge', 'v': '复仇'}, 
    {"n":"超能Superpower","v":"超能"},
    {"n":"修仙cultivation","v":"修仙"}, 
    {"n":"甜宠sweet","v":"甜宠"}, 
    {"n":"重生rebirth","v":"重生"}, 
    {"n":"反转reverse","v":"反转"}, 
    {"n":"玄幻Fantasy","v":"玄幻"}, 
    {"n":"脑洞blowing","v":"脑洞"},
    {'n': '音乐MUSIC', 'v': '音乐'}, 
    {'n': '演唱会concert', 'v': '演唱会'}, 
    {'n': '传记biography', 'v': '传记'}, 
    {'n': '惊悚thriller', 'v': '惊悚'}, 
    {'n': '恐怖horror', 'v': '恐怖'}, 
    {'n': '悬疑suspense', 'v': '悬疑'}, 
    {'n': '冒险adventure', 'v': '冒险'}, 
    {'n': '灵异supernatural', 'v': '灵异'}, 
    {'n': '爆笑laughter', 'v': '爆笑'}, 
    {'n': '穿越travel', 'v': '穿越'}, 
    {'n': '神话mythology', 'v': '神话'}
	]}, 
	{'key': '电视剧分类', 'name': '电视剧DRAMA', 'value': [
	{'n': '不限ALL', 'v': ''}, 
	{'n': '古装costume drama', 'v': '古装'}, 
    {'n': '战争WAR', 'v': '战争'}, 
    {'n': '喜剧comedy', 'v': '喜剧'}, 
    {'n': '丧尸zombie', 'v': '丧尸'}, 
    {'n': '吸血鬼vampire', 'v': '吸血鬼'}, 
    {'n': '抗战War', 'v': '抗战'}, 
    {'n': '犯罪crime', 'v': '犯罪'}, 
    {'n': '推理reasoning', 'v': '推理'}, 
    {'n': '邢侦Detective', 'v': '刑侦'}, 
    {'n': '法医Forensic', 'v': '法医'}, 
    {'n': '警匪police', 'v': '警匪'}, 
    {'n': '动作action', 'v': '动作'}, 
    {'n': '科幻sci-fi', 'v': '科幻'}, 
    {'n': '奇幻fantasy', 'v': '奇幻'}, 
    {'n': '改编adaptation', 'v': '改编'}, 
    {'n': '小说novel', 'v': '小说'}, 
    {'n': '动画animation', 'v': '动画'}, 
    {'n': '剧情Drama', 'v': '剧情'}, 
    {'n': '青春youth', 'v': '青春'}, 
    {'n': '谍战Spy', 'v': '谍战'}, 
    {'n': '偶像idol', 'v': '偶像'}, 
    {'n': '纪录record', 'v': '纪录'}, 
    {'n': '都市metropolis', 'v': '都市'}, 
    {'n': '家庭family', 'v': '家庭'}, 
    {'n': '复仇revenge', 'v': '复仇'}, 
    {"n":"超能Superpower","v":"超能"},
    {"n":"修仙cultivation","v":"修仙"}, 
    {"n":"甜宠sweet","v":"甜宠"}, 
    {"n":"重生rebirth","v":"重生"}, 
    {"n":"反转reverse","v":"反转"}, 
    {"n":"玄幻Fantasy","v":"玄幻"}, 
    {"n":"脑洞blowing","v":"脑洞"},
    {'n': '音乐MUSIC', 'v': '音乐'}, 
    {'n': '演唱会concert', 'v': '演唱会'}, 
    {'n': '传记biography', 'v': '传记'}, 
    {'n': '惊悚thriller', 'v': '惊悚'}, 
    {'n': '恐怖horror', 'v': '恐怖'}, 
    {'n': '悬疑suspense', 'v': '悬疑'}, 
    {'n': '冒险adventure', 'v': '冒险'}, 
    {'n': '灵异supernatural', 'v': '灵异'}, 
    {'n': '爆笑laughter', 'v': '爆笑'}, 
    {'n': '穿越travel', 'v': '穿越'}, 
    {'n': '神话mythology', 'v': '神话'}
	]}, 
{'key': '综艺形式', 'name': '综艺TVSHOW', 'value': [
	{'n': '不限ALL', 'v': ''}, 
	{'n': '真人秀reality', 'v': '真人秀'},
    {'n': '脱口秀脱口秀', 'v': '脱口秀'},  
    {'n': '游戏GAME', 'v': '游戏'}, 
    {'n': '亲子Parent child', 'v': '亲子'}, 
    {'n': '搞笑FUNNY', 'v': '搞笑'}
	]}, 
	{'key': '地区', 'name': '地区AREA', 'value': [
	{'n': '全部ALL', 'v': ''}, 
	{'n': '中国CN', 'v': '中国'}, 
    {'n': '香港HK', 'v': '香港'}, 
    {'n': '台湾TW', 'v': '台湾'}, 
    {'n': '韩国KR', 'v': '韩国'}, 
    {'n': '美国US', 'v': '美国'}, 
    {'n': '法国FRA', 'v': '法国'}, 
    {'n': '日本JP', 'v': '日本'}, 
    {'n': '马来西亚MY', 'v': '马来西亚'}, 
    {'n': '新加坡SG', 'v': '新加坡'}, 
    {'n': '泰国TH', 'v': '泰国'}, 
    {'n': '英国UK', 'v': '英国'}, 
    {'n': '俄罗斯RU', 'v': '俄罗斯'}, 
    {'n': '菲律宾PH', 'v': '菲律宾'}
	]}, 
	{'key': '年代', 'name': '年代YEAR', 'value': [
	{'n': '全部ALL', 'v': ''}, 
	{'n': '2026', 'v': '2026'}, 
    {'n': '2025', 'v': '2025'}, 
    {'n': '2024', 'v': '2024'}, 
    {'n': '2023', 'v': '2023'}, 
    {'n': '2022', 'v': '2022'}, 
    {'n': '2021', 'v': '2021'}, 
    {'n': '2020', 'v': '2020'}, 
    {'n': '2019', 'v': '2019'}, 
    {'n': '2018', 'v': '2018'}, 
    {'n': '2017', 'v': '2017'}, 
    {'n': '2016', 'v': '2016'}, 
    {'n': '2015', 'v': '2015'}, 
    {'n': '2014', 'v': '2014'}, 
    {'n': '2013', 'v': '2013'}, 
    {'n': '2012', 'v': '2012'}, 
    {'n': '2011', 'v': '2011'}, 
    {'n': '2010', 'v': '2010'}, 
    {'n': '2010年代', 'v': '2010年代'},
    {'n': '2000年代', 'v': '2000年代'},
    {'n': '90年代', 'v': '90年代'}
	]}, 
	{'key': '平台', 'name': '平台platform', 'value': [
	{'n': '全部ALL', 'v': ''}, 
	{'n': '腾讯TENXUN', 'v': '腾讯视频'},
	{'n': '爱奇艺AIQIYI', 'v': '爱奇艺'}, 
	{'n': '优酷YOUKU', 'v': '优酷'}, 
	{'n': '湖南HUNAN', 'v': '湖南卫视'},
	{'n': 'Netflix', 'v': 'Netflix'},
	{'n': 'HBO', 'v': 'HBO'}, 
	{'n': 'BBC', 'v': 'BBC'}, 
	{'n': 'NHK', 'v': 'NHK'}, 
	{'n': 'CBS', 'v': 'CBS'}, 
	{'n': 'NBC', 'v': 'NBC'}, 
	{'n': 'tvN', 'v': 'tvN'}
	]}]},
    limit:20,
    play_parse:false,
    推荐:'',
    推荐:'js:let d=[];let douban_api_host="http://api.douban.com/api/v2";let miniapp_apikey="0ac44ae016490db2204ce0a042db2916";const count=30;function miniapp_request(path,query){try{let url=douban_api_host+path;query.apikey=miniapp_apikey;fetch_params.headers=oheaders;url=buildUrl(url,query);let html=fetch(url,fetch_params);return JSON.parse(html)}catch(e){print("发生了错误:"+e.message);return{}}}function subject_real_time_hotest(){try{let res=miniapp_request("/subject_collection/subject_real_time_hotest/items",{});let lists=[];let arr=res.subject_collection_items||[];arr.forEach(function(item){if(item.type==="movie"||item.type==="tv"){let rating=item.rating?item.rating.value:"暂无评分";let honnor=(item.honor_infos||[]).map(function(it){return it.title}).join("|");lists.append({vod_id:"msearch:"+TYPE,vod_name:item.title||"",vod_pic:item.pic.normal,vod_remarks:rating+" "+honnor})}});return lists}catch(e){print("发生了错误:"+e.message);return[]}}VODS=subject_real_time_hotest();print(VODS);',
    // 手动调用解析请求json的url,此lazy不方便
    lazy:'',
    // 推荐:'.list_item;img&&alt;img&&src;a&&Text;a&&data-float',
    一级:'',
    一级:'js:let d=[];let douban=input.split("douban=")[1].split("&")[0];let douban_api_host="http://api.douban.com/api/v2";let miniapp_apikey="0ac44ae016490db2204ce0a042db2916";const count=30;function miniapp_request(path,query){try{let url=douban_api_host+path;query.apikey=miniapp_apikey;fetch_params.headers=oheaders;url=buildUrl(url,query);let html=fetch(url,fetch_params);if(/request_error/.test(html)){print(html)}return JSON.parse(html)}catch(e){print("发生了错误:"+e.message);return{}}}function cate_filter(d,douban){douban=douban||"";try{let res={};if(MY_CATE==="interests"){if(douban){let status=MY_FL.status||"mark";let subtype_tag=MY_FL.subtype_tag||"";let year_tag=MY_FL.year_tag||"全部";let path="/user/"+douban+"/interests";res=miniapp_request(path,{type:"movie",status:status,subtype_tag:subtype_tag,year_tag:year_tag,start:(MY_PAGE-1)*count,count:count})}else{return{}}}else if(MY_CATE==="hot_gaia"){let sort=MY_FL.sort||"recommend";let area=MY_FL.area||"全部";let path="/movie/"+MY_CATE;res=miniapp_request(path,{area:area,sort:sort,start:(MY_PAGE-1)*count,count:count})}else if(MY_CATE==="tv_hot"||MY_CATE==="show_hot"){let stype=MY_FL.type||MY_CATE;let path="/subject_collection/"+stype+"/items";res=miniapp_request(path,{start:(MY_PAGE-1)*count,count:count})}else if(MY_CATE.startsWith("rank_list")){let id=MY_CATE==="rank_list_movie"?"movie_real_time_hotest":"tv_real_time_hotest";id=MY_FL.榜单||id;let path="/subject_collection/"+id+"/items";res=miniapp_request(path,{start:(MY_PAGE-1)*count,count:count})}else{let path="/"+MY_CATE+"/recommend";let selected_categories;let tags;let sort;if(Object.keys(MY_FL).length>0){sort=MY_FL.sort||"T";tags=Object.values(MY_FL).join(",");if(MY_CATE==="movie"){selected_categories={"类型":MY_FL.类型||"","地区":MY_FL.地区||""}}else{selected_categories={"类型":MY_FL.类型||"","形式":MY_FL.类型?MY_FL.类型+"地区":"","地区":MY_FL.地区||""}}}else{sort="T";tags="";if(MY_CATE==="movie"){selected_categories={"类型":"","地区":""}}else{selected_categories={"类型":"","形式":"","地区":""}}}let params={tags:tags,sort:sort,refresh:0,selected_categories:stringify(selected_categories),start:(MY_PAGE-1)*count,count:count};res=miniapp_request(path,params)}let result={page:MY_PAGE,pagecount:Math.ceil(res.total/count),limit:count,total:res.total};let items=[];if(/^rank_list|tv_hot|show_hot/.test(MY_CATE)){items=res["subject_collection_items"]}else if(MY_CATE==="interests"){res["interests"].forEach(function(it){items.push(it.subject)})}else{items=res.items}let lists=[];items.forEach(function(item){if(item.type==="movie"||item.type==="tv"){let rating=item.rating?item.rating.value:"";let rat_str=rating||"暂无评分";let title=item.title;let honor=item.honor_infos||[];let honor_str=honor.map(function(it){return it.title}).join("|");let vod_obj={vod_name:title!=="未知电影"?title:"暂不支持展示",vod_pic:item.pic.normal,vod_remarks:rat_str+" "+honor_str};let vod_obj_d={url:item.type+"$"+item.id,title:title!=="未知电影"?title:"暂不支持展示",pic_url:item.pic.normal,desc:rat_str+" "+honor_str};lists.push(vod_obj);d.push(vod_obj_d)}});result.list=lists;return result}catch(e){print(e.message)}return{}}let res=cate_filter(d,douban);setResult2(res);',
    二级:'',
    搜索:'',
}
